# Generated by Django 4.2.4 on 2023-09-12 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_choice_votes_alter_question_pub_date_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 10, 21, 5, 279589, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
